version: 2.1

orbs:
  snyk: snyk/snyk@0.0.8

jobs:
  build:
    docker:
      - image: circleci/golang:1.13

    working_directory: /go/src/github.com/newrelic/go-insights
    steps:
      - checkout

      - run: make build-ci
      - snyk/scan

